# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ce62067d3c304b2a609db9f83dbb984eda26a6ac6c1dc7e6a949615fd97f1a3c5e53906eaf4f8b95356c8508055598a3622f95046b07cfad4d6cf5aa19b506e

test:
  secret_key_base: 7491f91b9a973d7e18eb1790a3162e8e48a091612684822025f273ade365f5db360ff53df10ae6e7c2fe9d1f01e5d699dc69ea8f1acd413f29d48d57e442d663

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
